### ISSUE TITLE
Integration of Dynamic RDT definitions

### ISSUE THREAD

**Issue by shivenbhatt1** [onaio/rdt-standard#460] opened 2020-08-28 14:02 UTC
Blocked by closing https://github.com/onaio/Covid19/issues/15

Set up a meeting with Sam and PLD on dynamic tasking

**Comment by vincent-karuri** [comment] 2020-11-09 12:56
Duplicate of https://github.com/onaio/rdt-standard/issues/511

**Closed by vincent-karuri** 2020-11-09 12:56 UTC
Labels: Android Client, blocked, covid response, enhancement
