### ISSUE TITLE
Unable to click the page - Bahasa Apps V1.7 (Built on Nov 7)

### ISSUE THREAD

**Issue by ellyasafaa** [onaio/rdt-standard#613] opened 2020-11-07 05:47 UTC
My apps running on Samsung A50s can't be clicked both for scanning and affixing the label manually.

This page seems to work at first, but the second time I tried it, it doesn't work.
![WhatsApp Image 2020-11-07 at 10 47 40 AM](https://user-images.githubusercontent.com/73918009/98433122-b3789580-20f6-11eb-9449-80ad27cce5fc.jpeg)

For these pages, they don't work since the beginning.
![WhatsApp Image 2020-11-07 at 10 47 40 AM (1)](https://user-images.githubusercontent.com/73918009/98433121-b1aed200-20f6-11eb-968f-0f7407a55900.jpeg)
![WhatsApp Image 2020-11-07 at 10 56 57 AM (2)](https://user-images.githubusercontent.com/73918009/98433118-af4c7800-20f6-11eb-8b17-d7f82861b8cc.jpeg)

**Comment by shivenbhatt1** [comment] 2020-11-09 13:01
@vincent-karuri I was able to replicate this on my google pixel

**Comment by vincent-karuri** [comment] 2020-11-09 14:45
I'm not able to replicate this. Are you clicking the arrow or the label?

**Comment by shivenbhatt1** [comment] 2020-11-09 14:54
@vincent-karuri Clicking anywhere, either the arrow or the label doesn't work. Tried logging off and back on, closing app, still didn't work.

**Comment by vincent-karuri** [comment] 2020-11-09 14:59
Could you share the steps for reproducing?

And is it the case that the last 2 screens don't work at all?

**Comment by shivenbhatt1** [comment] 2020-11-09 15:07
@vincent-karuri Fresh install of RDT App->Covid Patient 2->RDT->Location->Choose RDT Type (Stuck here). I am unable to select manual or barcode.

Interestingly it doesn't happen on the J7 that I also tested it with. But it happens on the Pixel.

I cleared the stored data in the app after and retried it after logging in. Same issue occurs.

**Comment by vincent-karuri** [comment] 2020-11-09 15:11
What are the specs for the pixel? model, android version etc.

**Comment by shivenbhatt1** [comment] 2020-11-09 15:21
Pixel 3 XL, Android Version 10

**Comment by vincent-karuri** [comment] 2020-11-09 15:40
@ellyasafaa what Android version are you on?

@shivenbhatt1 what Android version is the J7 on?

**Comment by shivenbhatt1** [comment] 2020-11-09 15:44
@vincent-karuri Samsung J727A, Android Version 8.1.0

**Comment by vincent-karuri** [comment] 2020-11-09 16:09
> Pixel 3 XL, Android Version 10, I did all the recent software updates last week

@shivenbhatt1 I've tried replicating this on an emulator with the same specs and still can't reproduce. Note that native forms does not currently fully support Android 10 and there's some ongoing work to fix [this](https://github.com/OpenSRP/opensrp-client-native-form/pull/491).

This will need more investigation if it's confirmed to affect versions other than 10.

My Samsung A8 is Android 9 and works fine. And I've used the same app on lower versions as well.

**Comment by shivenbhatt1** [comment] 2020-11-09 16:11
@vincent-karuri that is good to know. Let me test out another phone that is pre android 10, then update it to see if the problem occurs.

**Comment by ellyasafaa** [comment] 2020-11-12 11:40
@shivenbhatt1 @vincent-karuri I have tried it on another phone (OPPO A5s Android version 8.1.0) and the same issue occurs as on the Samsung A50s Android version 10

**Comment by vincent-karuri** [comment] 2020-11-16 06:55
@ellyasafaa have you tried clicking on the text itself and probably giving a few seconds to see if there's some kind of delay?

**Comment by shivenbhatt1** [comment] 2020-11-16 14:36
@vincent-karuri I tried this out as well since same thing is happening to me. Waiting 1 minute after selecting the arrow and the text. No response. There isn't a response for manual selection of RDTs either.

**Comment by vincent-karuri** [comment] 2020-11-16 15:01
@shivenbhatt1 is this for the Android 10 phone? I was looking to confirm what is being reported for the `OPPO A5s Android version 8.1.0` phone.

**Comment by shivenbhatt1** [comment] 2020-11-16 15:08
@vincent-karuri yes, I was running an android 10 on a Nokia 6.1

**Comment by ellyasafaa** [comment] 2020-11-18 00:00
@vincent-karuri Yes, I have tried to click on the text itself and there was no response

**Comment by vincent-karuri** [comment] 2020-11-18 07:35
@ellyasafaa for which phone?

**Comment by ellyasafaa** [comment] 2020-11-18 09:40
@vincent-karuri Both OPPO A5s Android version 8.1.0 and Samsung A50s Android version 10. I'll try on the other phone who has a lower Android version and tell you the result asap

**Comment by ellyasafaa** [comment] 2020-11-18 11:08
@vincent-karuri @shivenbhatt1  I've tried on Redmi S2 Android Version 8.1.0 and found no issue. But, for another OPPO A5s Android version 8.1.0 still found the issue in the Delivery Preparation part. I have sent the video to Shiven if you would like to check on that

**Comment by vincent-karuri** [comment] 2020-11-24 13:02
@shivenbhatt1 @ellyasafaa I have tried this on `OPPO A5s Android version 8.1.0 ` and `v1.7.0-CONFIGURABLE-RDT-SID-DEBUG` and everything works as expected. I've found no issue with clicking. 

Could you verify that OneScan is installed on the phone?

Also, please make sure you have the most up-to-date APK and make sure to uninstall the existing app before installing the most up-to-date APK.

**Comment by vincent-karuri** [comment] 2020-11-24 13:33
@shivenbhatt1 @ellyasafaa I was finally able to reproduce the labels being unclickable.

It only happens on an outdated version of the app. The app has to crash first after scanning a sample barcode (which is already fixed). After crashing, the app relaunches itself into the patient profile page. From here if you open the shipment form and try to click on the labels, they don't work.

This should not be a problem any more since the scan crash bug is fixed.

**Comment by vincent-karuri** [comment] 2020-12-02 05:51
This is fixed.

**Closed by vincent-karuri** 2020-12-02 05:51 UTC
Labels: Android Client, Priority - high, bug, covid response
