### ISSUE TITLE
Oversized(Inconsistent) text on the Supporting Investigations and Sample collection pages√

### ISSUE THREAD

**Issue by Mstjamush** [onaio/rdt-standard#344] opened 2020-08-03 12:46 UTC
![20200803_150617](https://user-images.githubusercontent.com/29072646/89183765-68536180-d5a0-11ea-82d5-5dfd24183857.jpg)

**Comment by vincent-karuri** [comment] 2020-08-12 07:53
Is duplicate of https://github.com/onaio/rdt-standard/issues/350

**Closed by vincent-karuri** 2020-08-12 07:53 UTC
Labels: Android Client, QA, covid response
