### ISSUE TITLE
Information Display Issue on Bahasa App

### ISSUE THREAD

**Issue by ellyasafaa** [onaio/rdt-standard#643] opened 2020-12-02 03:35 UTC
The information was not displayed as it is supposed to be. I used Samsung A50S Android version 10 and checked for several times (On 25, 26, 27, 30 Nov 2020, and 1 Dec 2020), but there was no change. It also appeared on another phone like Samsung S8, Nokia 8. Please see the detail in PDF File below

[Information Display Issue_SID.pdf](https://github.com/onaio/rdt-standard/files/5626809/Information.Display.Issue_SID.pdf)

**Comment by vincent-karuri** [comment] 2020-12-02 05:35
Closing this as a duplicate of https://github.com/onaio/rdt-standard/issues/631 and https://github.com/onaio/rdt-standard/issues/629.

**Closed by vincent-karuri** 2020-12-02 05:35 UTC
